AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 132
  AllowURI: true
  URISchemes:
    - http
    - https

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Metrics/AbcSize:
  Max: 23

Metrics/MethodLength:
  Max: 32

Style/FrozenStringLiteralComment:
  Enabled: false
